spring.application.name=Banking_System_Management_DB

server.port=8082

spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=bank_db
spring.datasource.password=wiz@linux

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

logging.file.name=banking-app.log
logging.level.root=debug
logging.level.com.mini_banking=trace

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always